ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa_droplet
ansible_host_key_checking: false

app_name: my-app
app_dir: /opt/my-app

docker_app_image: "ghcr.io/tahatsahin/SmartEdu:latest"
docker_app_port: 3000

nginx_server_name: "_"

mongo_root_user: root
mongo_root_password: "examplepassword"
mongo_db_name: "mydb"
